### ISSUE TITLE
Accept file paths from CLI arguments

### ISSUE THREAD

**Issue by gudvinr** [sun-jiao/flut-renamer#10]
Now, if you pass any CLI argument, they simply get ignored.  
Thus, you can't integrate flut-renamer to existing desktop environments because you can only open an app and then open files from it.

To make it usable as utility (e.g. in file managers) it should be possible to launch an app with file locations passed as CLI arguments, like `flut-renamer file1 file2 file3 etc`.

**Comment by sun-jiao** [comment]
It's possible because the dart language can accept command line parameter. While it can be a bit difficult to integrate them into the file manager's context menu. And I don't think this operation will be more easy than drag-and-drop.

**Comment by gudvinr** [comment]
I created this issue for CLI arguments specifically. Integration into different environments would be more involved so I didn't plan to cover it here.

But for future reference, if you're interested:
- on windows (up to 11 I believe) it's [relatively simple](https://learn.microsoft.com/en-us/windows/win32/shell/fa-verbs)
- on KDE it's [comparably simple](https://develop.kde.org/docs/apps/dolphin/service-menus/)

However, both methods still need to be able to pass arguments to an app.

**Comment by sun-jiao** [comment]
OK 👌, thanks for your detailed explanation. Do you mean using `flut-renamer file1 file2 file3 etc` to open the app with `file1 file2 file3 etc` being added to the file list?
