### ISSUE TITLE
Add monocrome Icon

### ISSUE THREAD

**Issue by Solovertical** [sun-jiao/flut-renamer#16]
https://m3.material.io/styles/icons/overview

![Screenshot_2024-05-21-06-32-25-833_com miui home](https://github.com/sun-jiao/flut-renamer/assets/109901807/21920077-81eb-4267-8079-2be323a8beaa)
It just look out of place

**Comment by sun-jiao** [comment]
![image](https://github.com/user-attachments/assets/4517a097-3827-45c1-84c4-ee63381e7215)
