### ISSUE TITLE
[FR] Text Generator and Capitalization

### ISSUE THREAD

**Issue by Solovertical** [sun-jiao/flut-renamer#17]
Love this app, Since this app is all about text editing, will you plan for more feature in future other than file Renaming, like text generator and capitalization.

## 1. **Text Generator**

![Screenshot_2024-05-22-08-48-53-502_io github forkmaintainers iceraven](https://github.com/sun-jiao/flut-renamer/assets/109901807/9d51076b-9a9a-4a5d-82ec-fdbda046dc79)

* Bold Text: Create text that is bolded.
  * Bold
  * Bold Cursive
  * Bold Italics (Serif)
  * Bold Italics (Sans Serif)
  * Small Text
  * Strikethrough
  * Underline
  * Italics
  * Cursive
  * Backwards
  * Bubble
  * Small Caps
  * Upside Down

* Italics: Generate italic text.
  * Italic
  * Italic Cursive
  * Italics Bold (Serif)
  * Italics Bold (Sans Serif)
  * Small Text
  * Cursive
  * Backwards
  * Bubble
  * Strikethrough
  * Underline
  * Small Caps
  * Upside Down  

 * Cursive: Generate cursive font.
   * Cursive
   * Bold Cursive
   * Bold Italics (Serif)
   * Bold Italics (Sans Serif)
   * Small Text
   * Strikethrough
   * Underline
   * Italics
   * Small Caps

* Small Text: Create subscript versions of text
* Underline Text
* Strikethrough Text
* Fancy Text

## 2. **Capitalize My Title**

![IMG_20240522_091840](https://github.com/sun-jiao/flut-renamer/assets/109901807/7fe7610e-a5c3-418e-b74a-90934fefbb43)

Top Tabs

* APA: Capitalize using the APA style guide.
* Chicago: Capitalize using the Chicago Manual of Style capitalization rules.
* AP: Use the Associated Press Stylebook capitalization guidelines.
* MLA: Use the MLA Handbook title capitalization rules.
* BB: Use the Bluebook title capitalization rules.
* AMA: Use the AMA Manual of Style capitalization rules.
* NY Times: Use the NY Times style guidelines.
* Wikipedia: Use Wikipedia’s capitalization rules.
* Email: Use proper capitalization rules for email.

Bottom Buttons

* Title Case: Capitalize only the words that should be capitalized according to the top tab style guide.
* Sentence Case: Capitalize only the first word of each sentence.
*  Uppercase: Convert your title from lowercase to uppercase.
* Lowercase: Convert your title from uppercase to lowercase.
* First Letter / Proper Case: Capitalize the first letter of every word.
* Alt Case: Capitalize every other letter of your text starting with the first letter being capitalized.
* Toggle Case: Change the case of every letter in your string. Similar to the Microsoft Word feature.

Other Options

* Straight quotes: Curly quotes (“,”,‘,’) are used in good typography. If you need to use straight quotes, enable this feature.
* Get Headline Score/Get Email Subject Score: Find out how strong your headline or email subject is by using our convenient tools.

**Comment by sun-jiao** [comment]
Close. Because it is out of scope for this project. Perhaps I'll consider creating another project to implement these features.
